spring.application.name=virtual_academy

# Database Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/swe_academy}
spring.datasource.username=${DB_USERNAME:academy_admin}
spring.datasource.password=${DB_PASSWORD}

# Database Management
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Useful for seeing the SQL queries your Java code sends to MySQL
spring.jpa.show-sql=true

# Enable placeholder replacement in Flyway scripts
spring.flyway.placeholder-replacement=true
spring.flyway.placeholders.admin_password_hash=${admin_password_hash}
spring.flyway.placeholders.admin_email=${admin_email}
spring.flyway.placeholders.admin_username=${admin_username}

# JWT Configuration
jwt.secret=${JWT_SECRET}

jwt.expirationMs=${JWT_EXPIRATION_MS}
jwt.refreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}