spring.application.name=virtual_academy

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/swe_academy
spring.datasource.username=academy_admin
spring.datasource.password=${DB_PASSWORD}

# Database Management
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

# Useful for seeing the SQL queries your Java code sends to MySQL
spring.jpa.show-sql=true

